### ISSUE TITLE
High Level issues

### ISSUE THREAD

**Issue by Andrew-Roide** [Andrew-Roide/code-journal-react#1]
## ✅ Task List

- [ ] Create a React App.
- [ ] Break UI into component hierarchy. 
- [ ] Categorize each button with an eventListener that should have onClick instead. 
- [ ] Identify where state should live. 
- [ ] In data.js  have exported functions for getting, adding, updating, and removing entries from the data model.
- [ ] Use React conditional rendering instead of the HTML hidden attribute.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
