### ISSUE TITLE
User can create an entry.

### ISSUE THREAD

**Issue by Andrew-Roide** [Andrew-Roide/code-journal-react#2]
## ✅ Task List

- [x] Create a React App.
- [x] Break UI into component hierarchy. 
- [x] Categorize each button with an eventListener that should have onClick instead. 
  - [x] Submit button should be onClick event handler.
  - [x] Move logic from main.js into component for submit.
  - [x] Remove logic for data.view and data.editing.
- [x] Identify where state should live. 
- [x] In data.js  have exported functions for getting, adding, updating, and removing entries from the data model.
- [x] Test the app by submitting some new entries and then reloading the page to confirm that:
  - [x] the data model is being saved to `localStorage` before each page reload.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
