### ISSUE TITLE
User can view their entries

### ISSUE THREAD

**Issue by Andrew-Roide** [Andrew-Roide/code-journal-react#3]
## ✅ Task List

- [ ] Have navbar 
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
